"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](lun_orange)\
$os\
$username\
[](bg:lun_yellow fg:lun_orange)\
$directory\
[](fg:lun_yellow bg:lun_cyan)\
$git_branch\
$git_status\
[](fg:lun_cyan bg:lun_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$ruby\
[](fg:lun_blue bg:lun_violet)\
$docker_context\
[](fg:lun_violet bg:bg_1)\
$time\
[ ](fg:bg_1)\
$line_break$character"""

palette = 'selenized_light'

[palettes.selenized_light]
# background and content tones:
bg_0 = '#fbf3db'
bg_1 = '#ece3cc'
bg_2 = '#d5cdb6'
dim_0 = '#909995'
fg_0 = '#53676d'
fg_1 = '#3a4d53'
# accent colors:
lun_red = '#d2212d'
lun_magenta = '#ca4898'
lun_orange = '#c25d1e'
lun_yellow = '#ad8900'
lun_green = '#489100'
lun_blue = '#0072d4'
lun_cyan = '#009c8f'
lun_violet = '#8762c6'

[os]
disabled = false
style = "bg:lun_orange fg:bg_0"

[os.symbols]
Macos = ""
Ubuntu = "󰕈"
Windows = "󰍲"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Raspbian = "󰐿"
Redhat = "󱄛"
SUSE = ""
Mint = "󰣭"
Manjaro = ""

[username]
show_always = true
style_user = "bg:lun_orange fg:bg_0"
style_root = "bg:lun_orange fg:bg_0"
format = '[ $user ]($style)'

[directory]
style = "bg:lun_yellow fg:bg_0"
read_only_style = "bg:lun_yellow fg:lun_magenta"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Code" = "󰲋 "
"workspace" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:lun_cyan"
format = '[[ $symbol $branch ](fg:bg_0 bg:lun_cyan)]($style)'

[git_status]
style = "bg:lun_cyan"
format = '[[($all_status$ahead_behind )](fg:bg_0 bg:lun_cyan)]($style)'

[nodejs]
symbol = ""
style = "bg:lun_blue"
format = '[[ $symbol( $version) ](fg:bg_0 bg:lun_blue)]($style)'

[c]
symbol = " "
style = "bg:lun_blue"
format = '[[ $symbol( $version) ](fg:bg_0 bg:lun_blue)]($style)'

[rust]
symbol = ""
style = "bg:lun_blue"
format = '[[ $symbol( $version) ](fg:bg_0 bg:lun_blue)]($style)'

[golang]
symbol = ""
style = "bg:lun_blue"
format = '[[ $symbol( $version) ](fg:bg_0 bg:lun_blue)]($style)'

[php]
symbol = ""
style = "bg:lun_blue"
format = '[[ $symbol( $version) ](fg:bg_0 bg:lun_blue)]($style)'

[java]
symbol = " "
style = "bg:lun_blue"
format = '[[ $symbol( $version) ](fg:bg_0 bg:lun_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:lun_blue"
format = '[[ $symbol( $version) ](fg:bg_0 bg:lun_blue)]($style)'

[haskell]
symbol = ""
style = "bg:lun_blue"
format = '[[ $symbol( $version) ](fg:bg_0 bg:lun_blue)]($style)'

[python]
symbol = ""
style = "bg:lun_blue"
format = '[[ $symbol( $version) ](fg:bg_0 bg:lun_blue)]($style)'

[ruby]
symbol = ""
style = "bg:lun_blue"
format = '[[ $symbol( $version) ](fg:bg_0 bg:lun_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:bg_1"
format = '[[ $symbol( $context) ](fg:bg_0 bg:lun_violet)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:bg_0"
format = '[[  $time ](fg:fg_0 bg:bg_1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:lun_green)'
error_symbol = '[✗](bold fg:lun_red)'
vimcmd_symbol = '[V](bold fg:lun_green) '
vimcmd_replace_one_symbol = '[❮](bold fg:lun_violet)'
vimcmd_replace_symbol = '[❮](bold fg:lun_violet)'
vimcmd_visual_symbol = '[❮](bold fg:lun_yellow)'
